### ISSUE TITLE
Connection time out (located in HK)

### ISSUE THREAD

**Issue by yangyxt** [pstawinski/pygenebe#4]
I just found this connection error: 

Traceback (most recent call last):
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/yangyxt/miniforge3/envs/acmg_bench/lib/python3.12/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f425c103d70>, 'Connection to api.genebe.net timed out. (connect timeout=None)')

I tried to ping api.genebe.net and got nothing in return. 

![image](https://github.com/user-attachments/assets/9a4deeee-a842-44d8-8ce8-56a07944d6a2)

I guess maybe you can check whether your end have some network security protocols blocking the request ?

**Comment by yangyxt** [comment]
I just tried to run this genebe on my macbook with a VPN enabled. It succesfully ping api.genebe.net but then I run into another issue: 

[genebe_err.log](https://github.com/user-attachments/files/18134410/genebe_err.log)

It is still related to the api connection. Please take a look. Thanks!

**Comment by pstawinski** [comment]
Hi, does the problem persist?
